snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/10.yaml

packages:
- .

extra-deps:
  - xmobar-0.50
  - hashtables-1.4.2

flags:
  xmobar:
    with_alsa: true
